### PR TITLE
Abdelski's contributions

### LINKED ISSUE #5: Add unit tests
Currently we have 56 tests and 9 of them are being ignored. We need to implement those tests and maybe try to add some more tests

### LINKED ISSUE #7: Generate Code Coverage Report

### PR DESCRIPTION
**Pull request by abdelski**
- Added jacoco plugin into our project
- Added code coverage report
- Extended test suits to improve code coverage
- Extended documentation.

### CODE REVIEW

**Review by conztantinee — CHANGES_REQUESTED** [review]
The update to Gradle and the adjustment of deprecated configurations has been executed successfully. The implications include improved build performance and future-proofing the project, underlining the need to keep our build tools updated.

Looking at the coverage metrics provided by JaCoCo, I can see that pinpointClass(Model, Resource, PropertyDescriptor) method in the RDFMapper class has low coverage. Extending test cases for that class is a good idea. 

About the modifications in RDFMapperTests.java: I suggest deleting the commented lines of code if they are no longer required, then merging.

**Comment by SubhanHakverdiyev** [comment]
We have conflict with two files namely **RDFMapper** and **documentation.md** . I think we should either store all documentations in one folder or add them all to the root folder but different name(anyway we need different name as they are conflicting).

**Comment by ayazbekobbelek** [comment]
> We have conflict with two files namely **RDFMapper** and **documentation.md** . I think we should either store all documentations in one folder or add them all to the root folder but different name(anyway we need different name as they are conflicting).

I think we can just resolve the merge conflict, I will resolve it, just someone needs to add more tests, hence increase the code coverage

**Comment by SubhanHakverdiyev** [comment]
> > We have conflict with two files namely **RDFMapper** and **documentation.md** . I think we should either store all documentations in one folder or add them all to the root folder but different name(anyway we need different name as they are conflicting).
> 
> I think we can just resolve the merge conflict, I will resolve it, just someone needs to add more tests, hence increase the code coverage

For RDFMapper yes we can solve but for documentation name should be changed

**Comment by ayazbekobbelek** [comment]
> > > We have conflict with two files namely **RDFMapper** and **documentation.md** . I think we should either store all documentations in one folder or add them all to the root folder but different name(anyway we need different name as they are conflicting).
> > 
> > 
> > I think we can just resolve the merge conflict, I will resolve it, just someone needs to add more tests, hence increase the code coverage
> 
> For RDFMapper yes we can solve but for documentation name should be changed

what do you mean by changing a name? I think resolving a conflict in documentation is easy, and will not take much time to resolve it

**Review by conztantinee — APPROVED** [review]
Everything seems good to go now. I'm approving to merge. I will work on extending tests to increase coverage.

**Pull request merged**
